# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_msfastar_wrappers", use_symbols = TRUE, package_name = "msfastar")

#' @docType package
#' @usage NULL
#' @useDynLib msfastar, .registration = TRUE
NULL

#' Return cleaned seqeuence
#' @export
sequence_prep <- function(s) .Call(wrap__sequence_prep, s)

#' Return cleaned seqeuence
#' @export
protease <- function(sequence, regex, partial, lower_pep_len, upper_pep_len, remove_m) .Call(wrap__protease, sequence, regex, partial, lower_pep_len, upper_pep_len, remove_m)


# nolint end
